"""Initial migration

Revision ID: 89f470e9157b
Revises: e4bacfd271c0
Create Date: 2026-09-02 11:30:51.143231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89f470e9157b'
down_revision: Union[str, None] = 'e4bacfd271c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_events_created_at'), table_name='events')
	op.drop_index(op.f('ix_events_device'), table_name='events')
	op.drop_index(op.f('ix_events_device_type'), table_name='events')
	op.drop_index(op.f('ix_events_event_type'), table_name='events')
	op.drop_table('events')
	op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
	op.drop_index(op.f('ix_tags_epc'), table_name='tags')
	op.drop_index(op.f('ix_tags_tid'), table_name='tags')
	op.drop_table('tags')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'tags',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column('device', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('epc', mysql.VARCHAR(length=24), nullable=False),
		sa.Column('tid', mysql.VARCHAR(length=24), nullable=True),
		sa.Column('ant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
		sa.Column('rssi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_tags_tid'), 'tags', ['tid'], unique=False)
	op.create_index(op.f('ix_tags_epc'), 'tags', ['epc'], unique=False)
	op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
	op.create_table(
		'events',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column('device', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('event_type', mysql.VARCHAR(length=50), nullable=False),
		sa.Column('event_data', mysql.TEXT(), nullable=False),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
	op.create_index(op.f('ix_events_device_type'), 'events', ['device', 'event_type'], unique=False)
	op.create_index(op.f('ix_events_device'), 'events', ['device'], unique=False)
	op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
	# ### end Alembic commands ###
