"""Initial migration

Revision ID: 9af6d2e05653
Revises: 89f470e9157b
Create Date: 2026-09-02 11:34:11.299366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af6d2e05653'
down_revision: Union[str, None] = '89f470e9157b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'events',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('device', sa.String(length=100), nullable=False),
		sa.Column('event_type', sa.String(length=50), nullable=False),
		sa.Column('event_data', sa.Text(), nullable=False),
		sa.Column(
			'created_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
	op.create_index(op.f('ix_events_device'), 'events', ['device'], unique=False)
	op.create_index('ix_events_device_type', 'events', ['device', 'event_type'], unique=False)
	op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
	op.create_table(
		'tags',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('device', sa.String(length=100), nullable=False),
		sa.Column('epc', sa.String(length=24), nullable=False),
		sa.Column('tid', sa.String(length=24), nullable=True),
		sa.Column('ant', sa.Integer(), nullable=True),
		sa.Column('rssi', sa.Integer(), nullable=True),
		sa.Column(
			'created_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
	op.create_index(op.f('ix_tags_epc'), 'tags', ['epc'], unique=False)
	op.create_index(op.f('ix_tags_tid'), 'tags', ['tid'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_tags_tid'), table_name='tags')
	op.drop_index(op.f('ix_tags_epc'), table_name='tags')
	op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
	op.drop_table('tags')
	op.drop_index(op.f('ix_events_event_type'), table_name='events')
	op.drop_index('ix_events_device_type', table_name='events')
	op.drop_index(op.f('ix_events_device'), table_name='events')
	op.drop_index(op.f('ix_events_created_at'), table_name='events')
	op.drop_table('events')
	# ### end Alembic commands ###
