"""Initial migration

Revision ID: b2c32553cdc5
Revises: c4998dd0e29c
Create Date: 2026-07-27 15:34:11.521814

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2c32553cdc5'
down_revision: Union[str, None] = 'c4998dd0e29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'generated_licenses', 'customer', existing_type=mysql.VARCHAR(length=255), nullable=True
	)
	op.alter_column(
		'generated_licenses', 'hardware_id', existing_type=mysql.VARCHAR(length=255), nullable=False
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'generated_licenses', 'hardware_id', existing_type=mysql.VARCHAR(length=255), nullable=True
	)
	op.alter_column(
		'generated_licenses', 'customer', existing_type=mysql.VARCHAR(length=255), nullable=False
	)
	# ### end Alembic commands ###
