"""no need id

Revision ID: c4998dd0e29c
Revises: 148ab160600b
Create Date: 2026-07-27 15:31:53.887669

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4998dd0e29c'
down_revision: Union[str, None] = '148ab160600b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'generated_licenses',
		'generated_by_id',
		existing_type=mysql.INTEGER(display_width=11),
		nullable=True,
	)
	op.alter_column(
		'generated_licenses',
		'generated_by_username',
		existing_type=mysql.VARCHAR(length=255),
		nullable=True,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'generated_licenses',
		'generated_by_username',
		existing_type=mysql.VARCHAR(length=255),
		nullable=False,
	)
	op.alter_column(
		'generated_licenses',
		'generated_by_id',
		existing_type=mysql.INTEGER(display_width=11),
		nullable=False,
	)
	# ### end Alembic commands ###
