"""add reader test info

Revision ID: d7f825d36f3c
Revises: b2c32553cdc5
Create Date: 2026-09-02 11:01:22.217601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7f825d36f3c'
down_revision: Union[str, None] = 'b2c32553cdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_events_created_at'), table_name='events')
	op.drop_index(op.f('ix_events_device'), table_name='events')
	op.drop_index(op.f('ix_events_device_created'), table_name='events')
	op.drop_index(op.f('ix_events_device_type'), table_name='events')
	op.drop_index(op.f('ix_events_event_type'), table_name='events')
	op.drop_index(op.f('ix_events_type_created'), table_name='events')
	op.drop_table('events')
	op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
	op.drop_index(op.f('ix_tags_device'), table_name='tags')
	op.drop_index(op.f('ix_tags_device_epc'), table_name='tags')
	op.drop_index(op.f('ix_tags_epc'), table_name='tags')
	op.drop_index(op.f('ix_tags_tid'), table_name='tags')
	op.drop_table('tags')
	op.drop_column('readers', 'can_generate_license')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		'readers',
		sa.Column(
			'can_generate_license',
			mysql.TINYINT(display_width=1),
			autoincrement=False,
			nullable=True,
		),
	)
	op.create_table(
		'tags',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column('device', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('epc', mysql.VARCHAR(length=24), nullable=False),
		sa.Column('tid', mysql.VARCHAR(length=24), nullable=True),
		sa.Column('ant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
		sa.Column('rssi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_tags_tid'), 'tags', ['tid'], unique=False)
	op.create_index(op.f('ix_tags_epc'), 'tags', ['epc'], unique=False)
	op.create_index(op.f('ix_tags_device_epc'), 'tags', ['device', 'epc'], unique=False)
	op.create_index(op.f('ix_tags_device'), 'tags', ['device'], unique=False)
	op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
	op.create_table(
		'events',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column('device', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('event_type', mysql.VARCHAR(length=50), nullable=False),
		sa.Column('event_data', mysql.TEXT(), nullable=False),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(
		op.f('ix_events_type_created'), 'events', ['event_type', 'created_at'], unique=False
	)
	op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
	op.create_index(op.f('ix_events_device_type'), 'events', ['device', 'event_type'], unique=False)
	op.create_index(
		op.f('ix_events_device_created'), 'events', ['device', 'created_at'], unique=False
	)
	op.create_index(op.f('ix_events_device'), 'events', ['device'], unique=False)
	op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
	# ### end Alembic commands ###
