"""reader test info

Revision ID: e4bacfd271c0
Revises: d7f825d36f3c
Create Date: 2026-09-02 11:12:48.194481

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4bacfd271c0'
down_revision: Union[str, None] = 'd7f825d36f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'events',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('device', sa.String(length=100), nullable=False),
		sa.Column('event_type', sa.String(length=50), nullable=False),
		sa.Column('event_data', sa.Text(), nullable=False),
		sa.Column(
			'created_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
	op.create_index(op.f('ix_events_device'), 'events', ['device'], unique=False)
	op.create_index('ix_events_device_type', 'events', ['device', 'event_type'], unique=False)
	op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
	op.create_table(
		'tags',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('device', sa.String(length=100), nullable=False),
		sa.Column('epc', sa.String(length=24), nullable=False),
		sa.Column('tid', sa.String(length=24), nullable=True),
		sa.Column('ant', sa.Integer(), nullable=True),
		sa.Column('rssi', sa.Integer(), nullable=True),
		sa.Column(
			'created_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
	op.create_index(op.f('ix_tags_epc'), 'tags', ['epc'], unique=False)
	op.create_index(op.f('ix_tags_tid'), 'tags', ['tid'], unique=False)
	op.drop_index(op.f('ix_licenses_created_at'), table_name='licenses')
	op.drop_index(op.f('ix_licenses_public_key'), table_name='licenses')
	op.drop_table('licenses')
	op.drop_index(op.f('ix_generated_licenses_created_at'), table_name='generated_licenses')
	op.drop_index(op.f('ix_generated_licenses_id'), table_name='generated_licenses')
	op.drop_table('generated_licenses')
	op.drop_index(op.f('ix_readers_type_created_at'), table_name='readers_type')
	op.drop_index(op.f('ix_readers_type_name'), table_name='readers_type')
	op.drop_table('readers_type')
	op.drop_index(op.f('ix_readers_available'), table_name='readers')
	op.drop_index(op.f('ix_readers_created_at'), table_name='readers')
	op.drop_index(op.f('ix_readers_hostname'), table_name='readers')
	op.drop_index(op.f('ix_readers_reader_type_id'), table_name='readers')
	op.drop_index(op.f('ix_readers_serial_number'), table_name='readers')
	op.drop_table('readers')
	op.drop_index(op.f('ix_orders_activated_at'), table_name='orders')
	op.drop_index(op.f('ix_orders_client_cnpj'), table_name='orders')
	op.drop_index(op.f('ix_orders_client_name'), table_name='orders')
	op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
	op.drop_index(op.f('ix_orders_label_code'), table_name='orders')
	op.drop_index(op.f('ix_orders_mounted_at'), table_name='orders')
	op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
	op.drop_index(op.f('ix_orders_product_code'), table_name='orders')
	op.drop_index(op.f('ix_orders_product_serial'), table_name='orders')
	op.drop_index(op.f('ix_orders_reader_id'), table_name='orders')
	op.drop_index(op.f('ix_orders_shipped_at'), table_name='orders')
	op.drop_index(op.f('ix_orders_tested_at'), table_name='orders')
	op.drop_table('orders')
	op.drop_index(op.f('ix_users_created_at'), table_name='users')
	op.drop_index(op.f('ix_users_email'), table_name='users')
	op.drop_index(op.f('ix_users_role'), table_name='users')
	op.drop_index(op.f('ix_users_username'), table_name='users')
	op.drop_table('users')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'users',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
		sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
		sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
	op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
	op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
	op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
	op.create_table(
		'orders',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column(
			'order_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
		),
		sa.Column('client_name', mysql.VARCHAR(length=255), nullable=False),
		sa.Column('client_cnpj', mysql.VARCHAR(length=25), nullable=True),
		sa.Column('product_code', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('product_description', mysql.VARCHAR(length=255), nullable=True),
		sa.Column('product_family', mysql.VARCHAR(length=255), nullable=True),
		sa.Column(
			'product_serial', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
		),
		sa.Column('label_code', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('reader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
		sa.Column('mounted_at', mysql.DATETIME(), nullable=True),
		sa.Column('tested_at', mysql.DATETIME(), nullable=True),
		sa.Column('shipped_at', mysql.DATETIME(), nullable=True),
		sa.Column('activated_at', mysql.DATETIME(), nullable=True),
		sa.Column(
			'created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
		),
		sa.Column(
			'mounted_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
		),
		sa.Column('tested_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
		sa.Column(
			'shipped_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
		),
		sa.Column(
			'activated_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
		),
		sa.Column('comments', mysql.TEXT(), nullable=True),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_orders_tested_at'), 'orders', ['tested_at'], unique=False)
	op.create_index(op.f('ix_orders_shipped_at'), 'orders', ['shipped_at'], unique=False)
	op.create_index(op.f('ix_orders_reader_id'), 'orders', ['reader_id'], unique=False)
	op.create_index(op.f('ix_orders_product_serial'), 'orders', ['product_serial'], unique=False)
	op.create_index(op.f('ix_orders_product_code'), 'orders', ['product_code'], unique=False)
	op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
	op.create_index(op.f('ix_orders_mounted_at'), 'orders', ['mounted_at'], unique=False)
	op.create_index(op.f('ix_orders_label_code'), 'orders', ['label_code'], unique=True)
	op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
	op.create_index(op.f('ix_orders_client_name'), 'orders', ['client_name'], unique=False)
	op.create_index(op.f('ix_orders_client_cnpj'), 'orders', ['client_cnpj'], unique=False)
	op.create_index(op.f('ix_orders_activated_at'), 'orders', ['activated_at'], unique=False)
	op.create_table(
		'readers',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column(
			'reader_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
		),
		sa.Column('serial_number', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('hostname', mysql.VARCHAR(length=255), nullable=True),
		sa.Column('available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_readers_serial_number'), 'readers', ['serial_number'], unique=True)
	op.create_index(op.f('ix_readers_reader_type_id'), 'readers', ['reader_type_id'], unique=False)
	op.create_index(op.f('ix_readers_hostname'), 'readers', ['hostname'], unique=False)
	op.create_index(op.f('ix_readers_created_at'), 'readers', ['created_at'], unique=False)
	op.create_index(op.f('ix_readers_available'), 'readers', ['available'], unique=False)
	op.create_table(
		'readers_type',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
		sa.Column('description', mysql.TEXT(), nullable=True),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_readers_type_name'), 'readers_type', ['name'], unique=True)
	op.create_index(
		op.f('ix_readers_type_created_at'), 'readers_type', ['created_at'], unique=False
	)
	op.create_table(
		'generated_licenses',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column(
			'generated_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
		),
		sa.Column('generated_by_username', mysql.VARCHAR(length=255), nullable=True),
		sa.Column('customer', mysql.VARCHAR(length=255), nullable=True),
		sa.Column('days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
		sa.Column('expires_at', mysql.DATETIME(), nullable=False),
		sa.Column('license_key', mysql.TEXT(), nullable=False),
		sa.Column('hardware_id', mysql.VARCHAR(length=255), nullable=False),
		sa.Column(
			'internal_use', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True
		),
		sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_generated_licenses_id'), 'generated_licenses', ['id'], unique=False)
	op.create_index(
		op.f('ix_generated_licenses_created_at'), 'generated_licenses', ['created_at'], unique=False
	)
	op.create_table(
		'licenses',
		sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
		sa.Column('public_key', mysql.VARCHAR(length=700), nullable=False),
		sa.Column('private_key', mysql.TEXT(), nullable=False),
		sa.Column(
			'created_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.Column(
			'updated_at',
			mysql.DATETIME(),
			server_default=sa.text('current_timestamp()'),
			nullable=False,
		),
		sa.PrimaryKeyConstraint('id'),
		mysql_collate='utf8mb4_general_ci',
		mysql_default_charset='utf8mb4',
		mysql_engine='InnoDB',
	)
	op.create_index(op.f('ix_licenses_public_key'), 'licenses', ['public_key'], unique=True)
	op.create_index(op.f('ix_licenses_created_at'), 'licenses', ['created_at'], unique=False)
	op.drop_index(op.f('ix_tags_tid'), table_name='tags')
	op.drop_index(op.f('ix_tags_epc'), table_name='tags')
	op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
	op.drop_table('tags')
	op.drop_index(op.f('ix_events_event_type'), table_name='events')
	op.drop_index('ix_events_device_type', table_name='events')
	op.drop_index(op.f('ix_events_device'), table_name='events')
	op.drop_index(op.f('ix_events_created_at'), table_name='events')
	op.drop_table('events')
	# ### end Alembic commands ###
