AVAILABLE_DEVICES = {
	'XPAD': {
		'tests': {
			'connection': False,
			'reading': False,
			'tag': False,
			'serial_number': False,
		},
		'config': {
			'READER': 'X714',
			'BUZZER': True,
			'SESSION': 0,
			'START_READING': True,
			'READ_POWER': 20,
		},
	},
	'X714': {
		'tests': {
			'connection': False,
			'reading': False,
			'tag': False,
			'serial_number': False,
			'read_ant_1': False,
			'read_ant_2': False,
			'read_ant_3': False,
			'read_ant_4': False,
			'usb_power_source': False,
			'ext_power_source': False,
		},
		'config': {
			'READER': 'X714',
			'BUZZER': True,
			'SESSION': 0,
			'START_READING': True,
			'READ_POWER': 20,
			'ACTIVE_ANT': [1, 2, 3, 4],
		},
	},
	'R700': {
		'tests': {
			'connection': False,
			'reading': False,
			'tag': False,
			'serial_number': False,
			'read_ant_1': False,
			'read_ant_2': False,
			'read_ant_3': False,
			'read_ant_4': False,
		},
		'config': {
			'READER': 'R700_IOT',
			'IP': '192.168.1.101',
			'USERNAME': 'root',
			'PASSWORD': 'impinj',
			'START_READING': True,
			'SESSION': 0,
			'ACTIVE_ANT': [1, 2, 3, 4],
			'READ_POWER': 20,
			'READ_RSSI': -80,
			'SEARCH_MODE': 'single-target',
			'RF_MODE': 4,
			'GPI_START': False,
			'FIRMWARE_VERSION': '8.4.1',
		},
	},
}
